name: RenovateBot

on:
  schedule:
    - cron: '0/15 * * * *'
  push:
    branches: [main]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: RenovateBot
        uses: renovatebot/github-action@v32
        with:
          configurationFile: default.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'info'
